### ISSUE TITLE
Long time on SELECT for certain devices

### ISSUE THREAD

**Issue by markarupert** [litehelpers/Cordova-sqlite-evcore-extbuild-free#15] opened 2016-12-30 17:02 UTC
On a few devices, e.g. Galaxy S6 it is frequently taking a very long time for a simple SELECT statement. The statement below can take as long as 161 seconds to come back. Other times it will take less than 100 milliseconds. At the very bottom is the table structure.

It was happening on the Cordova-sqlite-storage plugin so I installed this plugin as you recommended and I am still seeing the problem. 

You mentioned possible causes may be:

- Java-side garbage collection cycles
- Delays due to sqlite disk I/O

Is there something I can do to trouble shoot this?

//=====================================================
var startCheckElogLock = new Date().getTime();
var deferred = $q.defer();

var sql = "SELECT * FROM elog WHERE starttime >=" + logDate + " AND starttime < " + (logDate + DAY_UNIX) + " AND status = 4 ORDER BY starttime";
appDB.exeDBSQL(sql)
.then(function (r) {
deviceLog("checkElogLock: Run Time Get the time for lock: " + (new Date().getTime() - startCheckElogLock), function (str) {console.log(str)});
deferred.resolve();
}
});
//=====================================================

//=====================================================
// SQL EXECUTER
//=====================================================
app.service('appDB', function($q, $rootScope) {
function exeDBSQL(sql, param) {
var deferred = $q.defer();
db.executeSql(sql, [], function (results) {
sqlResult = new Object();
sqlResult.return = true;
sqlResult.tx = 0;
sqlResult.param = param;
sqlResult.sql = sql;
sqlResult.results = results;
$rootScope.unableToRecordData = false;
deferred.resolve(sqlResult);
}, function (err) {
sqlResult = new Object();
sqlResult.sql = sql;
sqlResult.return = false;
sqlResult.tx = -1;
sqlResult.err = err;
$rootScope.unableToRecordData = true;
deviceLog("appDB.exeDBSQL Failed, err=" + err.message, function (str) {console.log(str)});
deferred.resolve(sqlResult);
});
return deferred.promise;
}

 return {
     exeDBSQL: exeDBSQL
 };
});

//======================================================
tx.executeSql("CREATE TABLE IF NOT EXISTS elog (status, starttime, endtime)");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN lat TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN lon TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN uploaded TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN city TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN state TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN inspectiontime TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN defects TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN violation TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN reason TEXT NOT NULL DEFAULT ''");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN odometer TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN assetid TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN inspectionassetid TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN resolvedby TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN resolution TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN parts TEXT");
appDB.exeDBSQL("ALTER TABLE elog ADD COLUMN eventstatus TEXT");
tx.executeSql("CREATE INDEX IF NOT EXISTS timeStatusElogIdx ON elog (starttime, endtime, status)");
//=============================================================

**Comment by brodybits** [comment] 2017-01-02 14:37
You can try using the Chrome web inspector with your app to see if the delays come from the JavaScript or native side. On the native side cordova-sqlite-storage uses both Java and C (NDK) while this version does most of the processing in NDK C code.

To get help from the community you may want to make a self-contained test project, **without** use of Ionic or other Angular derivatives.

**Comment by markarupert** [comment] 2017-01-03 18:18
My biggest challenge with this is the inability to recreate the problem on any devices that I have "in hand". I have a remote tester that seems to have the problem but I do not have any debugging access to the device. 

I don't suppose there is any way to get diagnostics returned back up through the plugin to do some diagnosis?

**Comment by brodybits** [comment] 2017-01-03 19:03
Hi @markarupert,

Assuming you see the same issue with both Cordova-sqlite-storage and this version I become suspicious that there is something in the JavaScript, either in your application or the plugin, and would suggest adding some more logging to help pinpoint the delay. You may want to try this in the Cordova-sqlite-storage version since it has a more permissive source license.

Here are the recommended time log points (with proper labels) in SQLitePlugin.js from the main cordova-sqlite-storage version:
```js
--- a/www/SQLitePlugin.js
+++ b/www/SQLitePlugin.js
@@ -238,30 +238,31 @@
   SQLitePlugin.prototype.executeSql = function(statement, params, success, error) {
     var myerror, myfn, mysuccess;
     mysuccess = function(t, r) {
       if (!!success) {
         return success(r);
       }
     };
     myerror = function(t, e) {
       if (!!error) {
         return error(e);
       }
     };
     myfn = function(tx) {
       tx.addStatement(statement, params, mysuccess, myerror);
     };
+    // maybe log here
     this.addTransaction(new SQLitePluginTransaction(this, myfn, null, null, false, false));
   };
 
   SQLitePlugin.prototype.sqlBatch = function(sqlStatements, success, error) {
     var batchList, j, len1, myfn, st;
     if (!sqlStatements || sqlStatements.constructor !== Array) {
       throw newSQLError('sqlBatch expects an array');
     }
     batchList = [];
     for (j = 0, len1 = sqlStatements.length; j < len1; j++) {
       st = sqlStatements[j];
       if (st.constructor === Array) {
         if (st.length === 0) {
           throw newSQLError('sqlBatch array element of zero (0) length');
         }
@@ -307,30 +308,31 @@
     this.readOnly = readOnly;
     this.executes = [];
     if (txlock) {
       this.addStatement("BEGIN", [], null, function(tx, err) {
         throw newSQLError("unable to begin transaction: " + err.message, err.code);
       });
     } else {
       this.addStatement("SELECT 1", [], null, null);
     }
   };
 
   SQLitePluginTransaction.prototype.start = function() {
     var err;
     try {
       this.fn(this);
+      // maybe log here
       this.run();
     } catch (error1) {
       err = error1;
       txLocks[this.db.dbname].inProgress = false;
       this.db.startNextTransaction();
       if (this.error) {
         this.error(newSQLError(err));
       }
     }
   };
 
   SQLitePluginTransaction.prototype.executeSql = function(sql, values, success, error) {
     if (this.finalized) {
       throw {
         message: 'InvalidStateError: DOM Exception 11: This transaction is already finalized. Transactions are committed after its success or failure handlers are called. If you are using a Promise to handle callbacks, be aware that implementations following the A+ standard adhere to run-to-completion semantics and so Promise resolution occurs on a subsequent tick and therefore after the transaction commits.',
@@ -390,30 +392,31 @@
       throw newSQLError("a statement with no error handler failed: " + response.message, response.code);
     }
     if (handler(this, response) !== false) {
       throw newSQLError("a statement error callback did not return false: " + response.message, response.code);
     }
   };
 
   SQLitePluginTransaction.prototype.run = function() {
     var batchExecutes, handlerFor, i, mycb, mycbmap, request, tropts, tx, txFailure, waiting;
     txFailure = null;
     tropts = [];
     batchExecutes = this.executes;
     waiting = batchExecutes.length;
     this.executes = [];
     tx = this;
+    // log here
     handlerFor = function(index, didSucceed) {
       return function(response) {
         var err;
         if (!txFailure) {
           try {
             if (didSucceed) {
               tx.handleStatementSuccess(batchExecutes[index].success, response);
             } else {
               tx.handleStatementFailure(batchExecutes[index].error, newSQLError(response));
             }
           } catch (error1) {
             err = error1;
             txFailure = newSQLError(err);
           }
         }
@@ -433,51 +436,55 @@
     i = 0;
     while (i < batchExecutes.length) {
       request = batchExecutes[i];
       mycbmap[i] = {
         success: handlerFor(i, true),
         error: handlerFor(i, false)
       };
       tropts.push({
         qid: null,
         sql: request.sql,
         params: request.params
       });
       i++;
     }
     mycb = function(result) {
+      // log here
       var j, q, r, ref, res, resultIndex, type;
       for (resultIndex = j = 0, ref = result.length - 1; 0 <= ref ? j <= ref : j >= ref; resultIndex = 0 <= ref ? ++j : --j) {
         r = result[resultIndex];
         type = r.type;
         res = r.result;
         q = mycbmap[resultIndex];
         if (q) {
           if (q[type]) {
             q[type](res);
           }
         }
       }
+      // log here
     };
+    // log here
     cordova.exec(mycb, null, "SQLitePlugin", "backgroundExecuteSqlBatch", [
       {
         dbargs: {
           dbname: this.db.dbname
         },
         executes: tropts
       }
     ]);
+    // log here
   };
 
   SQLitePluginTransaction.prototype.abort = function(txFailure) {
     var failed, succeeded, tx;
     if (this.finalized) {
       return;
     }
     tx = this;
     succeeded = function(tx) {
       txLocks[tx.db.dbname].inProgress = false;
       tx.db.startNextTransaction();
       if (tx.error) {
         tx.error(txFailure);
       }
     };
```

If we see the delay comes from the Java/native side then I can give you some more pointers.

**Comment by markarupert** [comment] 2017-01-16 03:23
Christopher,

 

Sorry it has taken me a while to respond to this.

 

I have been out of town and the device that is giving me the problem is in Colorado and I am in FL. So I had to build the app with diagnostics and iterate back and forth with the user.

 

Below are 2 diagnostic lines and below that a code snippet. It seems that it is taking in this case 14 seconds to initiate the transaction.             

01/15/2017 19:14:49 - appDB.exeDBSQL START (1484532889793) 

01/15/2017 19:15:03 - appDB.exeDBSQL EXE   (1484532889793)

 

 

1:            var nowVal = new Date().getTime();

2:            deviceLog("appDB.exeDBSQL START ("+ nowVal +")", function (str) {console.log(str)});

3:            db.transaction(

4:                 function (tx) {

5:                     deviceLog("appDB.exeDBSQL EXE ("+nowVal+") ", function (str) {console.log(str)});

6:                     tx.executeSql(sql, values, function (tx, results) {

7:                             deviceLog("appDB.exeDBSQL passed ("+(new Date().getTime()-nowVal)+", "+ nowVal +") ", function (str) {console.log(str)});

8:                         },

9:                         function (err) {

10:                             deviceLog("appDB.exeDBSQL Failed", function (str) {console.log(str)});

11:                         });

12:                 }, function (e) {

13:                     deviceLog("appDB.exeDBSQL Transaction Failed ("+sqlResult.err+")", function (str) {console.log(str)});

14:                 }, function () {

15:                 }

16:             );

 

 

Mark A. Rupert, President - RGi

One of the worst things we can do in business is an excellent job at something that didn’t need to be done in the first place.

---------------------------------------------------

This electronic message transmission contains information from The Rupert Group, Inc. that may be proprietary, confidential and/or privileged. The information is intended only for the use of the individual(s) or entity named above. If you are not the intended recipient, be aware that any disclosure, copying or distribution or use of the contents of this information is prohibited. If you have received this electronic transmission in error, please notify the sender immediately by replying to the address listed in the "From:" field.

**Comment by brodybits** [comment] 2017-01-31 19:11
@markarupert sorry for the delay. I think the issue is that transactions are queued and run in sequence. I will document this as a pitfall when I get a chance.

**Comment by markarupert** [comment] 2017-01-31 21:17
I doing more investigating and this seems to be due to the app being suspended on some Android devices and giving them very little processing time.  So I am not sure it is related to the plugin itself.

**Comment by brodybits** [comment] 2017-01-31 21:22
That makes sense, thanks. Closing for now, please be sure to report if you run into any more issues.

**Closed by brodybits** 2017-01-31 21:22 UTC
Labels: discussion, documentation, info needed, question, testing
